### PR TITLE
fix: Uncaught error: operation cancelled now handled

### PR DESCRIPTION
**Pull request by ebebbington**

### CODE REVIEW

**Comment by ebebbington** [comment]
tried a second method, didnt work, reverted back to the first, and now that doesnt work for some reason lol

**Comment by uki00a** [comment]
@ebebbington Thanks for opening this PR!

> tried a second method, didnt work, reverted back to the first, and now that doesnt work for some reason lol

It seems to be failing on [the exit sanitizer](https://deno.land/manual@v1.18.1/testing/sanitizers#exit-sanitizer) :thinking: Could you add logging using `console.error()` below instead of calling `Deno.exit()`?

https://github.com/denodrivers/redis/blob/b3bb75bc0c0818c0931d6925e0f6305b200cb684/protocol/reply.ts#L60-L61

**Comment by ebebbington** [comment]
@uki00a i think the underlying issue is that its still trying to read when the conn is closed, dont know the odebase enough but i think a try/catch or `if this.conn.is_closed` would be needed for the 'main' logic that reads

**Comment by ebebbington** [comment]
and the reason the test fails is because we arent returning anything in the catch, so the ending `throw` call is called

**Comment by ebebbington** [comment]
> @ebebbington I looked into the cause of this problem and found that the cause was actually in the test code (#291)
> 
> Either way, thanks for taking the time to investigate this problem! 🙇

Np! glad the problem was fixed in the end, one way or another

**Pull request closed without merging**
